spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ef-sak

no.nav.security.jwt:
  issuer:
    sts:
      discoveryurl: ${STS_DISCOVERY_URL}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}

AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token

INFOTRYGD_FEED_API_URL: https://familie-ef-infotrygd-feed.dev.adeo.no
INFOTRYGD_REPLIKA_API_URL: https://infotrygd-enslig-forsoerger.dev.adeo.no
FAMILIE_BREV_API_URL: https://familie-brev.dev.intern.nav.no
FAMILIE_BLANKETT_API_URL: https://familie-ef-blankett.dev.intern.nav.no
FRONTEND_OPPGAVE_URL: https://ensligmorellerfar.dev.intern.nav.no/oppgavebenk
rolle:
  veileder: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"
  beslutter: "01166863-22f1-4e16-9785-d7a05a22df74"
  saksbehandler: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"