spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

DEPLOY_ENV: dev
ON_PREM_URL_ENV: dev

FRONTEND_OPPGAVE_URL: https://ensligmorellerfar.intern.dev.nav.no/oppgavebenk

G_OMREGNING_CRON_EXPRESSION: 0 0 * * * ?
DEAKTIVER_MIKROFRONTEND_CRON_EXPRESSION: 0 30 14 * * ? #kl 14:30 hver dag

rolle:
  veileder: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"
  beslutter: "01166863-22f1-4e16-9785-d7a05a22df74"
  saksbehandler: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"
  kode6: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
  kode7: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
  egenAnsatt: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
  forvalter: "c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b" # teamfamilie-forvaltning

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS 928636f4-fd0d-4149-978e-a6fb68bb19de

KAFKA_BROKERS: hostname:1234
KAFKA_KEYSTORE_PATH: kafkaKeystorePath
KAFKA_CREDSTORE_PASSWORD: kafkaCredstorePassword
KAFKA_TRUSTSTORE_PATH: kafkaTruststorePath

FAMILIE_TILBAKE_URL: http://tilbakekreving-backend.tilbake
